# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
