# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.CharField(max_length=255),
        ),
    ]
